### ISSUE TITLE
А где SPA?

### ISSUE THREAD

**Issue by Pum-purum** [Clasen00/simple-spa#3]
Хочу увидеть, как переход между страницами происходит без перезагрузки страницы, но к сожалению тут только одна страница, и увидеть этого нельзя. Я так понял, на странице должен быть список созданных issue, но их тоже почему-то ни одного нет, хотя создание issue работает, и в базе они присутствуют. Можно довести до ума репозиторий? Нам всем очень нужны SPA

**Comment by Clasen00** [comment]
Большое спасибо, что высказали свою точку зрения!

К сожалению, SPA тут никогда не появится, я забросил этот репозиторий из за отсутствия времени на его доведение до ума
